import Crypto.Assumption.DL.DDH
import Crypto.Infrastructure.Computation.FirstOrder.Algebra

namespace CryptoConstruction.Primitive.Encryption.AsymmetricEncryption.ElGamal

open Crypto.Infrastructure.Computation.Cost

universe uCost uScalar uGroup

variable {M : CostModel.{uCost}}

/-- ElGamal parameter families are the underlying DLog/DDH families. -/
abbrev Family (M : CostModel.{uCost}) :=
  Crypto.Assumption.DL.DDH.Family.{uCost, uScalar, uGroup} M

/-- ElGamal public parameters are generated by the underlying DLog/DDH family. -/
abbrev PublicParam (M : CostModel.{uCost}) :=
  Crypto.Assumption.DL.DDH.PublicParam.{uCost, uScalar, uGroup} M

/-- Public keys are group elements determined by the public parameters. -/
abbrev PublicKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- Secret keys are scalars determined by the public parameters. -/
abbrev SecretKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Scalar

/-- Messages are group elements determined by the public parameters. -/
abbrev Message (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- ElGamal ciphertexts are pairs of group elements determined by the public parameters. -/
abbrev Ciphertext (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier × pp.Carrier

/- The scalar and group carriers available to reified ElGamal algorithms. -/
namespace Language

inductive Base where
  | scalar
  | carrier
  deriving DecidableEq

abbrev scalarTy :
    Crypto.Infrastructure.Computation.FirstOrder.Ty Base :=
  .base .scalar

abbrev carrierTy :
    Crypto.Infrastructure.Computation.FirstOrder.Ty Base :=
  .base .carrier

/-- Interpret object-language carriers using one concrete DDH parameter. -/
abbrev interpret
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    Base → Type (max uScalar uGroup)
  | .scalar => ULift.{uGroup} pp.Scalar
  | .carrier => ULift.{uScalar} pp.Carrier

abbrev generator
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    Crypto.Infrastructure.Computation.FirstOrder.Ty.denote
      (interpret pp) carrierTy :=
  ULift.up pp.generator

abbrev ScalarValue
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  Crypto.Infrastructure.Computation.FirstOrder.Ty.denote
    (interpret pp) scalarTy

abbrev CarrierValue
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  Crypto.Infrastructure.Computation.FirstOrder.Ty.denote
    (interpret pp) carrierTy

abbrev liftScalar
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    pp.Scalar → ScalarValue pp :=
  ULift.up

abbrev liftCarrier
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    pp.Carrier → CarrierValue pp :=
  ULift.up

abbrev keyPairDown
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    CarrierValue pp × ScalarValue pp → pp.Carrier × pp.Scalar :=
  fun result => (result.1.down, result.2.down)

abbrev carrierPairDown
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    CarrierValue pp × CarrierValue pp → pp.Carrier × pp.Carrier :=
  fun result => (result.1.down, result.2.down)

/-- Exactly the first-order operations used by ElGamal algorithms. -/
inductive Operation :
    Crypto.Infrastructure.Computation.FirstOrder.Ty Base →
    Crypto.Infrastructure.Computation.FirstOrder.Ty Base → Type where
  | sampleScalar : Operation .unit scalarTy
  | smul : Operation (.prod scalarTy carrierTy) carrierTy
  | add : Operation (.prod carrierTy carrierTy) carrierTy
  | sub : Operation (.prod carrierTy carrierTy) carrierTy

def signature :
    Crypto.Infrastructure.Computation.FirstOrder.Signature Base where
  Op := Operation

/--
First-order adapter for the DDH parameter's authoritative exact algebra.
The adapter moves runtime arguments out of operation constructors and preserves
the DDH algebra's existing universe lifts and exact costs.
-/
noncomputable def algebra
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    Crypto.Infrastructure.Computation.FirstOrder.CostedAlgebra
      M (interpret pp) signature where
  exec operation args :=
    match operation with
    | .sampleScalar => pp.algebra.exec .sampleScalar
    | .smul => pp.algebra.exec (.smul args.1.down args.2.down)
    | .add => pp.algebra.exec (.add args.1.down args.2.down)
    | .sub => pp.algebra.exec (.sub args.1.down args.2.down)

end Language

end CryptoConstruction.Primitive.Encryption.AsymmetricEncryption.ElGamal
