import Crypto.Assumption.DL.DDH
import CryptoFirstOrder.Assumption.DL.DDH

namespace CryptoConstruction.Primitive.Encryption.AsymmetricEncryption.ElGamal

open scoped CryptoFirstOrder

universe uCost uScalar uGroup

variable
  (M : Crypto.Infrastructure.Computation.Cost.CostModel.{uCost})

/-- ElGamal parameter families are the underlying DLog/DDH families. -/
abbrev Family :=
  Crypto.Assumption.DL.DDH.Family.{uCost, uScalar, uGroup} M

/-- ElGamal public parameters are generated by the underlying DLog/DDH family. -/
abbrev PublicParam :=
  Crypto.Assumption.DL.DDH.PublicParam.{uCost, uScalar, uGroup} M

variable {M}

/-- Public keys are group elements determined by the public parameters. -/
abbrev PublicKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- Secret keys are scalars determined by the public parameters. -/
abbrev SecretKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Scalar

/-- Messages are group elements determined by the public parameters. -/
abbrev Message (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- ElGamal ciphertexts are pairs of group elements determined by the public parameters. -/
abbrev Ciphertext (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier × pp.Carrier

/- The scalar and group carriers available to reified ElGamal algorithms. -/
namespace Language

export CryptoFirstOrder.Assumption.DL.DDH
  (Base scalarTy carrierTy interpret ScalarValue CarrierValue liftScalar
    liftCarrier carrierScalarPairDown carrierPairDown Operation signature algebra)

/-- Object-language type of an ElGamal public key. -/
abbrev publicKeyTy := carrierTy

/-- Object-language type of an ElGamal secret key. -/
abbrev secretKeyTy := scalarTy

/-- Object-language type of an ElGamal message. -/
abbrev messageTy := carrierTy

/-- Object-language type of an ElGamal ciphertext. -/
abbrev ciphertextTy := carrierTy ×ₜ carrierTy

abbrev keyPairDown
    (pp : PublicParam.{uCost, uScalar, uGroup} M) :
    CarrierValue pp × ScalarValue pp → pp.Carrier × pp.Scalar :=
  carrierScalarPairDown pp

namespace Operation

export CryptoFirstOrder.Assumption.DL.DDH.Operation
  (sampleScalar smul add sub)

end Operation

end Language

end CryptoConstruction.Primitive.Encryption.AsymmetricEncryption.ElGamal
