name = "CryptoLib"
version = "0.1.0"
keywords = ["cryptography", "formal-verification", "lean"]
defaultTargets = ["CryptoLib.Core", "CryptoLib.Program",
  "CryptoLib.Instantiation", "CryptoLib.Test"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longLine = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc1"

[[lean_lib]]
name = "CryptoLib.Core"

[[lean_lib]]
name = "CryptoLib.Program"

[[lean_lib]]
name = "CryptoLib.Instantiation"

[[lean_lib]]
name = "CryptoLib.Test"
