import Crypto.Infrastructure.Computation.Algebra.Group
import Crypto.Infrastructure.Computation.Distribution
import Crypto.Infrastructure.GameBased.Indistinguishability
import Mathlib.Probability.ProbabilityMassFunction.Monad

namespace Crypto.Assumption.DL

namespace DDH

universe uScalar uGroup

/-- Public parameters for a finite additive-group DDH instance. -/
structure PublicParam where
  Scalar : Type uScalar
  Carrier : Type uGroup
  addGroup : AddGroup Carrier
  fintypeCarrier : Fintype Carrier
  nonemptyCarrier : Nonempty Carrier
  decidableEqCarrier : DecidableEq Carrier
  fintypeScalar : Fintype Scalar
  nonemptyScalar : Nonempty Scalar
  mulScalar : Mul Scalar
  smul : SMul Scalar Carrier
  generator : Carrier
  generator_generates : ∀ x : Carrier, ∃ a : Scalar, a • generator = x
  mulScalarAction :
    ∀ leftExp rightExp : Scalar,
      (leftExp * rightExp) • generator = leftExp • (rightExp • generator)
  compatibleScalarAction :
    ∀ secretKey nonce : Scalar,
      secretKey • (nonce • generator) = nonce • (secretKey • generator)

attribute [instance] PublicParam.addGroup
attribute [instance] PublicParam.fintypeCarrier
attribute [instance] PublicParam.nonemptyCarrier
attribute [instance] PublicParam.decidableEqCarrier
attribute [instance] PublicParam.fintypeScalar
attribute [instance] PublicParam.nonemptyScalar
attribute [instance] PublicParam.mulScalar
attribute [instance] PublicParam.smul

/-- A security-parameter-indexed family of DDH public parameters. -/
structure Family where
  setup : Crypto.SecPar → PMF PublicParam.{uScalar, uGroup}

/-- A DDH challenge consists of public parameters and three group elements. -/
structure ChallengeInput where
  param : PublicParam.{uScalar, uGroup}
  left : param.Carrier
  right : param.Carrier
  shared : param.Carrier

/-- A genuine DDH tuple generated by two exponents. -/
def realChallenge
    (pp : PublicParam.{uScalar, uGroup}) (a b : pp.Scalar) :
    ChallengeInput.{uScalar, uGroup} where
  param := pp
  left := a • pp.generator
  right := b • pp.generator
  shared := (a * b) • pp.generator

@[simp] theorem realChallenge_shared_eq_nestedAction
    (pp : PublicParam.{uScalar, uGroup}) (a b : pp.Scalar) :
    (realChallenge pp a b).shared = a • (b • pp.generator) :=
  pp.mulScalarAction a b

/-- A random DDH tuple where the third group element is uniform in the group. -/
def randomChallenge
    (pp : PublicParam.{uScalar, uGroup})
    (leftExp rightExp : pp.Scalar) (shared : pp.Carrier) : ChallengeInput.{uScalar, uGroup} where
  param := pp
  left := leftExp • pp.generator
  right := rightExp • pp.generator
  shared := shared

/-- The real DDH challenge distribution. -/
noncomputable def realSample
    (F : Family.{uScalar, uGroup}) :
    Crypto.SecPar → PMF ChallengeInput.{uScalar, uGroup} :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun rightExp =>
          PMF.pure (realChallenge pp leftExp rightExp)

/-- The random DDH challenge distribution. -/
noncomputable def randomSample
    (F : Family.{uScalar, uGroup}) :
    Crypto.SecPar → PMF ChallengeInput.{uScalar, uGroup} :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun rightExp =>
          PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Carrier)
            fun shared =>
              PMF.pure (randomChallenge pp leftExp rightExp shared)

/-- The distinguishing problem induced by a DDH family. -/
noncomputable def ddhProblem
    (F : Family.{uScalar, uGroup}) :
    Crypto.Infrastructure.GameBased.Distinguishing.Problem ChallengeInput.{uScalar, uGroup} where
  left := realSample F
  right := randomSample F

/-- The Decisional Diffie-Hellman assumption for a parameter family. -/
def Assumption (F : Family.{uScalar, uGroup}) : Prop :=
  Crypto.Infrastructure.GameBased.Distinguishing.Hard (ddhProblem F)

end DDH

end Crypto.Assumption.DL
