import Crypto.Assumption.DL.DLog
import Crypto.Infrastructure.Computation.Distribution
import Crypto.Infrastructure.GameBased.Indistinguishability
import Mathlib.Probability.ProbabilityMassFunction.Monad

namespace Crypto.Assumption.DL

namespace DDH

universe uParam uScalar uGroup

/-- A DDH challenge consists of public parameters and three group elements. -/
structure ChallengeInput (Param : Type uParam) (Group : Type uGroup) where
  param : Param
  left : Group
  right : Group
  shared : Group

section

variable {Param : Type uParam} {Scalar : Type uScalar} {Group : Type uGroup}
variable [AddGroup Group] [Fintype Group] [Nonempty Group] [DecidableEq Group]
variable [Fintype Scalar] [Nonempty Scalar] [Mul Scalar] [SMul Scalar Group]

/-- A genuine DDH tuple generated by two exponents. -/
def realChallenge
    (F : DLog.Family Param Scalar Group) (pp : Param)
    (leftExp rightExp : Scalar) : ChallengeInput Param Group where
  param := pp
  left := leftExp • F.generator pp
  right := rightExp • F.generator pp
  shared := (leftExp * rightExp) • F.generator pp

/-- A random DDH tuple where the third group element uses an independent exponent. -/
def randomChallenge
    (F : DLog.Family Param Scalar Group) (pp : Param)
    (leftExp rightExp sharedExp : Scalar) : ChallengeInput Param Group where
  param := pp
  left := leftExp • F.generator pp
  right := rightExp • F.generator pp
  shared := sharedExp • F.generator pp

/-- The real DDH challenge distribution. -/
noncomputable def realSample
    (F : DLog.Family Param Scalar Group) :
    Crypto.SecPar → PMF (ChallengeInput Param Group) :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF Scalar) fun rightExp =>
          PMF.pure (realChallenge F pp leftExp rightExp)

/-- The random DDH challenge distribution. -/
noncomputable def randomSample
    (F : DLog.Family Param Scalar Group) :
    Crypto.SecPar → PMF (ChallengeInput Param Group) :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF Scalar) fun rightExp =>
          PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF Scalar)
            fun sharedExp =>
              PMF.pure (randomChallenge F pp leftExp rightExp sharedExp)

/-- The distinguishing problem induced by a DDH family. -/
noncomputable def problem
    (F : DLog.Family Param Scalar Group) :
    Crypto.Infrastructure.GameBased.Distinguishing.Problem (ChallengeInput Param Group) where
  left := realSample F
  right := randomSample F

/-- The Decisional Diffie-Hellman assumption for a parameter family. -/
def Assumption (F : DLog.Family Param Scalar Group) : Prop :=
  Crypto.Infrastructure.GameBased.Distinguishing.Hard (problem F)

end

end DDH

end Crypto.Assumption.DL
