import Crypto.Infrastructure.Computation.Algebra.Group
import Crypto.Infrastructure.Computation.Distribution
import Crypto.Infrastructure.GameBased.Indistinguishability
import Mathlib.Probability.ProbabilityMassFunction.Monad

namespace Crypto.Assumption.DL

namespace DDH

universe uScalar uGroup

/-- Public parameters for a finite additive-group DDH instance. -/
structure PublicParam where
  Scalar : Type uScalar
  Carrier : Type uGroup
  addGroup : AddGroup Carrier
  fintypeCarrier : Fintype Carrier
  nonemptyCarrier : Nonempty Carrier
  decidableEqCarrier : DecidableEq Carrier
  fintypeScalar : Fintype Scalar
  nonemptyScalar : Nonempty Scalar
  mulScalar : Mul Scalar
  smul : SMul Scalar Carrier
  generator : Carrier

attribute [instance] PublicParam.addGroup
attribute [instance] PublicParam.fintypeCarrier
attribute [instance] PublicParam.nonemptyCarrier
attribute [instance] PublicParam.decidableEqCarrier
attribute [instance] PublicParam.fintypeScalar
attribute [instance] PublicParam.nonemptyScalar
attribute [instance] PublicParam.mulScalar
attribute [instance] PublicParam.smul

/-- A security-parameter-indexed family of DDH public parameters. -/
structure Family where
  setup : Crypto.SecPar → PMF PublicParam.{uScalar, uGroup}

/-- A DDH challenge consists of public parameters and three group elements. -/
structure ChallengeInput where
  param : PublicParam.{uScalar, uGroup}
  left : param.Carrier
  right : param.Carrier
  shared : param.Carrier

/-- A genuine DDH tuple generated by two exponents. -/
def realChallenge
    (pp : PublicParam.{uScalar, uGroup}) (leftExp rightExp : pp.Scalar) :
    ChallengeInput.{uScalar, uGroup} where
  param := pp
  left := leftExp • pp.generator
  right := rightExp • pp.generator
  shared := (leftExp * rightExp) • pp.generator

/-- A random DDH tuple where the third group element uses an independent exponent. -/
def randomChallenge
    (pp : PublicParam.{uScalar, uGroup})
    (leftExp rightExp sharedExp : pp.Scalar) : ChallengeInput.{uScalar, uGroup} where
  param := pp
  left := leftExp • pp.generator
  right := rightExp • pp.generator
  shared := sharedExp • pp.generator

/-- The real DDH challenge distribution. -/
noncomputable def realSample
    (F : Family.{uScalar, uGroup}) :
    Crypto.SecPar → PMF ChallengeInput.{uScalar, uGroup} :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun rightExp =>
          PMF.pure (realChallenge pp leftExp rightExp)

/-- The random DDH challenge distribution. -/
noncomputable def randomSample
    (F : Family.{uScalar, uGroup}) :
    Crypto.SecPar → PMF ChallengeInput.{uScalar, uGroup} :=
  fun sec =>
    PMF.bind (F.setup sec) fun pp =>
      PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun leftExp =>
        PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun rightExp =>
          PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar)
            fun sharedExp =>
              PMF.pure (randomChallenge pp leftExp rightExp sharedExp)

/-- The distinguishing problem induced by a DDH family. -/
noncomputable def ddhProblem
    (F : Family.{uScalar, uGroup}) :
    Crypto.Infrastructure.GameBased.Distinguishing.Problem ChallengeInput.{uScalar, uGroup} where
  left := realSample F
  right := randomSample F

/-- The Decisional Diffie-Hellman assumption for a parameter family. -/
def Assumption (F : Family.{uScalar, uGroup}) : Prop :=
  Crypto.Infrastructure.GameBased.Distinguishing.Hard (ddhProblem F)

end DDH

end Crypto.Assumption.DL
