import Crypto.Assumption.DL.DDH
import Crypto.Infrastructure.Computation.Distribution
import Crypto.Primitive.Encryption.AsymmetricEncryption.Syntax
import Mathlib.Probability.ProbabilityMassFunction.Monad

namespace Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal

universe uScalar uGroup

open Crypto.Primitive.Encryption.AsymmetricEncryption

/-- ElGamal public parameters are generated by the underlying DLog/DDH family. -/
abbrev PublicParam :=
  Crypto.Assumption.DL.DDH.PublicParam.{uScalar, uGroup}

/-- Public keys are group elements determined by the public parameters. -/
abbrev PublicKey (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier

/-- Secret keys are scalars determined by the public parameters. -/
abbrev SecretKey (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Scalar

/-- Messages are group elements determined by the public parameters. -/
abbrev Message (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier

/-- ElGamal ciphertexts are pairs of group elements determined by the public parameters. -/
abbrev Ciphertext (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier × pp.Carrier

/-- ElGamal over the public-parameter generator supplied by a DDH family. -/
noncomputable def scheme
    (F : Crypto.Assumption.DL.DDH.Family.{uScalar, uGroup}) :
    Scheme
      Crypto.SecPar
      PublicParam.{uScalar, uGroup}
      PublicKey
      SecretKey
      Message
      Ciphertext where
  setup := F.setup
  keygen := fun pp =>
    PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun secretKey =>
      PMF.pure (secretKey • pp.generator, secretKey)
  encrypt := fun pp publicKey message =>
    PMF.bind (Crypto.Infrastructure.Computation.Distribution.uniformPMF pp.Scalar) fun nonce =>
      PMF.pure (nonce • pp.generator, message + nonce • publicKey)
  decrypt := fun pp secretKey ciphertext =>
    let _ := pp
    ciphertext.2 - secretKey • ciphertext.1

end Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal
