import Crypto.Assumption.DL.DDH

namespace Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal

open Crypto.Infrastructure.Computation.Cost

universe uCost uScalar uGroup

variable {M : CostModel.{uCost}}

/-- ElGamal public parameters are generated by the underlying DLog/DDH family. -/
abbrev PublicParam (M : CostModel.{uCost}) :=
  Crypto.Assumption.DL.DDH.PublicParam.{uCost, uScalar, uGroup} M

/-- Public keys are group elements determined by the public parameters. -/
abbrev PublicKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- Secret keys are scalars determined by the public parameters. -/
abbrev SecretKey (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Scalar

/-- Messages are group elements determined by the public parameters. -/
abbrev Message (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier

/-- ElGamal ciphertexts are pairs of group elements determined by the public parameters. -/
abbrev Ciphertext (pp : PublicParam.{uCost, uScalar, uGroup} M) :=
  pp.Carrier × pp.Carrier

end Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal
