import Crypto.Assumption.DL.DDH

namespace Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal

universe uScalar uGroup

/-- ElGamal public parameters are generated by the underlying DLog/DDH family. -/
abbrev PublicParam :=
  Crypto.Assumption.DL.DDH.PublicParam.{uScalar, uGroup}

/-- Public keys are group elements determined by the public parameters. -/
abbrev PublicKey (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier

/-- Secret keys are scalars determined by the public parameters. -/
abbrev SecretKey (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Scalar

/-- Messages are group elements determined by the public parameters. -/
abbrev Message (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier

/-- ElGamal ciphertexts are pairs of group elements determined by the public parameters. -/
abbrev Ciphertext (pp : PublicParam.{uScalar, uGroup}) :=
  pp.Carrier × pp.Carrier

end Crypto.Primitive.Encryption.AsymmetricEncryption.Instantiations.ElGamal
